insert into departamento (nombre) values( 'Amazonas ');
insert into departamento (nombre) values( 'Antioquia ');
insert into departamento (nombre) values( 'Arauca ');
insert into departamento (nombre) values( 'Atlántico ');
insert into departamento (nombre) values( 'Bolívar ');
insert into departamento (nombre) values( 'Boyacá ');
insert into departamento (nombre) values( 'Caldas ');
insert into departamento (nombre) values( 'Caquetá ');
insert into departamento (nombre) values( 'Casanare ');
insert into departamento (nombre) values( 'Cauca ');
insert into departamento (nombre) values( 'Cesar ');
insert into departamento (nombre) values( 'Chocó ');
insert into departamento (nombre) values( 'Córdoba ');
insert into departamento (nombre) values( 'Cundinamarca ');
insert into departamento (nombre) values( 'Guainía ');
insert into departamento (nombre) values( 'Guaviare ');
insert into departamento (nombre) values( 'Huila ');
insert into departamento (nombre) values( 'La Guajira ');
insert into departamento (nombre) values( 'Magdalena ');
insert into departamento (nombre) values( 'Meta ');
insert into departamento (nombre) values( 'Nariño ');
insert into departamento (nombre) values( 'Norte de Santander ');
insert into departamento (nombre) values( 'Putumayo ');
insert into departamento (nombre) values( 'Quindío ');
insert into departamento (nombre) values( 'Risaralda ');
insert into departamento (nombre) values( 'San Andrés y Providencia ');
insert into departamento (nombre) values( 'Santander ');
insert into departamento (nombre) values( 'Sucre ');
insert into departamento (nombre) values( 'Tolima ');
insert into departamento (nombre) values( 'Valle del Cauca ');
insert into departamento (nombre) values( 'Vaupés ');
insert into departamento (nombre) values( 'Vichada ');
